-- MySQL Script generated by MySQL Workbench
-- Mon Aug 19 14:56:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aquareadpro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aquareadpro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aquareadpro` DEFAULT CHARACTER SET utf8mb3 ;
USE `aquareadpro` ;

-- -----------------------------------------------------
-- Table `aquareadpro`.`pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquareadpro`.`pago` ;

CREATE TABLE IF NOT EXISTS `aquareadpro`.`pago` (
  `idPago` TINYINT NOT NULL AUTO_INCREMENT,
  `monto` DOUBLE UNSIGNED NULL DEFAULT NULL,
  `fechaPago` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` TINYINT NULL DEFAULT '1',
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aquareadpro`.`tarifa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquareadpro`.`tarifa` ;

CREATE TABLE IF NOT EXISTS `aquareadpro`.`tarifa` (
  `idTarifa` TINYINT NOT NULL AUTO_INCREMENT,
  `tarifaMinima` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`idTarifa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aquareadpro`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquareadpro`.`usuario` ;

CREATE TABLE IF NOT EXISTS `aquareadpro`.`usuario` (
  `idUsuario` TINYINT NOT NULL AUTO_INCREMENT,
  `nickName` VARCHAR(30) NOT NULL,
  `password` VARCHAR(150) NOT NULL DEFAULT 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
  `nombre` VARCHAR(40) NOT NULL,
  `primerApellido` VARCHAR(30) NOT NULL,
  `segundoApellido` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `fono` VARCHAR(15) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `foto` VARCHAR(100) NULL DEFAULT NULL,
  `rol` TINYINT NOT NULL DEFAULT '0',
  `estado` TINYINT NOT NULL DEFAULT '2',
  `idAutor` TINYINT UNSIGNED NOT NULL,
  `fechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaActualizacion` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `nickName_UNIQUE` ON `aquareadpro`.`usuario` (`nickName` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `aquareadpro`.`usuario` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `aquareadpro`.`avisocobranza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquareadpro`.`avisocobranza` ;

CREATE TABLE IF NOT EXISTS `aquareadpro`.`avisocobranza` (
  `idAviso` TINYINT NOT NULL AUTO_INCREMENT,
  `totalPagar` DOUBLE NOT NULL,
  `fechaEmision` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaVencimiento` TIMESTAMP NULL DEFAULT NULL,
  `idAutor` TINYINT UNSIGNED NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1' COMMENT '1   --------->  vigente\\\\n0  ----------> vencido',
  `idPago` TINYINT NOT NULL,
  `idTarifa` TINYINT NOT NULL,
  `idUsuario` TINYINT NOT NULL,
  PRIMARY KEY (`idAviso`, `idTarifa`, `idUsuario`),
  CONSTRAINT `fk_avisoCobranza_Pago1`
    FOREIGN KEY (`idPago`)
    REFERENCES `aquareadpro`.`pago` (`idPago`),
  CONSTRAINT `fk_avisoCobranza_Tarifa1`
    FOREIGN KEY (`idTarifa`)
    REFERENCES `aquareadpro`.`tarifa` (`idTarifa`),
  CONSTRAINT `fk_avisocobranza_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `aquareadpro`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_avisoCobranza_Pago1_idx` ON `aquareadpro`.`avisocobranza` (`idPago` ASC) VISIBLE;

CREATE INDEX `fk_avisoCobranza_Tarifa1_idx` ON `aquareadpro`.`avisocobranza` (`idTarifa` ASC) VISIBLE;

CREATE INDEX `fk_avisocobranza_usuario1_idx` ON `aquareadpro`.`avisocobranza` (`idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `aquareadpro`.`datalogger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquareadpro`.`datalogger` ;

CREATE TABLE IF NOT EXISTS `aquareadpro`.`datalogger` (
  `idDatalogger` TINYINT NOT NULL AUTO_INCREMENT,
  `latitud` DECIMAL(10,8) NOT NULL,
  `longitud` DECIMAL(11,8) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaActualizacion` TIMESTAMP NULL DEFAULT NULL,
  `idAutor` TINYINT UNSIGNED NOT NULL,
  `idUsuario` TINYINT NOT NULL,
  PRIMARY KEY (`idDatalogger`),
  CONSTRAINT `fk_datalogger_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `aquareadpro`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_datalogger_usuario1_idx` ON `aquareadpro`.`datalogger` (`idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `aquareadpro`.`medidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquareadpro`.`medidor` ;

CREATE TABLE IF NOT EXISTS `aquareadpro`.`medidor` (
  `idMedidor` TINYINT NOT NULL AUTO_INCREMENT,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaActualizacion` TIMESTAMP NULL DEFAULT NULL,
  `idAutor` TINYINT UNSIGNED NOT NULL,
  `idDatalogger` TINYINT NOT NULL,
  PRIMARY KEY (`idMedidor`),
  CONSTRAINT `fk_medidor_datalogger1`
    FOREIGN KEY (`idDatalogger`)
    REFERENCES `aquareadpro`.`datalogger` (`idDatalogger`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_medidor_datalogger1_idx` ON `aquareadpro`.`medidor` (`idDatalogger` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `aquareadpro`.`lectura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquareadpro`.`lectura` ;

CREATE TABLE IF NOT EXISTS `aquareadpro`.`lectura` (
  `idLectura` TINYINT NOT NULL AUTO_INCREMENT,
  `lecturaActual` INT NOT NULL,
  `lecturaAnterior` INT NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaActualizacion` TIMESTAMP NULL DEFAULT NULL,
  `idAviso` TINYINT NOT NULL,
  `idMedidor` TINYINT NOT NULL,
  PRIMARY KEY (`idLectura`, `idAviso`),
  CONSTRAINT `fk_lectura_avisocobranza1`
    FOREIGN KEY (`idAviso`)
    REFERENCES `aquareadpro`.`avisocobranza` (`idAviso`),
  CONSTRAINT `fk_lectura_medidor1`
    FOREIGN KEY (`idMedidor`)
    REFERENCES `aquareadpro`.`medidor` (`idMedidor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_lectura_avisocobranza1_idx` ON `aquareadpro`.`lectura` (`idAviso` ASC) VISIBLE;

CREATE INDEX `fk_lectura_medidor1_idx` ON `aquareadpro`.`lectura` (`idMedidor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `aquareadpro`.`socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquareadpro`.`socio` ;

CREATE TABLE IF NOT EXISTS `aquareadpro`.`socio` (
  `idSocio` INT NOT NULL AUTO_INCREMENT,
  `numeroSocio` TINYINT NOT NULL,
  `idUsuario` TINYINT NOT NULL,
  PRIMARY KEY (`idSocio`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_Socio_Usuario1_idx` ON `aquareadpro`.`socio` (`idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `aquareadpro`.`usuario1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquareadpro`.`usuario1` ;

CREATE TABLE IF NOT EXISTS `aquareadpro`.`usuario1` (
  `idUsuario` TINYINT NOT NULL AUTO_INCREMENT,
  `nickName` VARCHAR(30) NOT NULL,
  `password` VARCHAR(150) NOT NULL DEFAULT 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
  `nombre` VARCHAR(40) NOT NULL,
  `primerApellido` VARCHAR(30) NOT NULL,
  `segundoApellido` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `fono` VARCHAR(15) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `foto` VARCHAR(100) NULL DEFAULT NULL,
  `rol` TINYINT NOT NULL DEFAULT '0',
  `estado` TINYINT NOT NULL DEFAULT '2',
  `idAutor` TINYINT NULL DEFAULT NULL,
  `fechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaActualizacion` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `nickName_UNIQUE` ON `aquareadpro`.`usuario1` (`nickName` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `aquareadpro`.`usuario1` (`email` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
